### ISSUE TITLE
DB statistics collection takes too long time

### ISSUE THREAD

**Issue by julmon** [osdldbt/dbt2#3]
When running `dbt2-run-workload` with a target duration set to 2 hours, database statistics takes almost 4 hours.

Command executed:
```shell
$ dbt2-run-workload -A -l 5444 -a pgsql -d 7200 -D dbt2 -F 2 -H 10.0.0.147 -n -o /tmp/dbt2-data-tde -s 37500 -t 1 -u -w 2000 -y -z "My report"
```

**Comment by mw2q** [comment]
One possibility is that the time it takes to collect stats could be taking long enough that each iteration of collection stats continues to extend how long this script is actually going to run.  The dbt2-pgsql-db-stat script doesn't account for how long the commands take to run, even though they are all fired off into the background.

We can explore adding an additional check to see how much time has passed and quit when either the requested iterations expired or when we've run longer than the expected duration.

I don't think this explains why the time is doubled in a 2 hour test but at least we can put in some mechanism to try not to run longer that the test is supposed to.

**Comment by markwkm** [comment]
Closing, hopefully fixed with script updates.
